version: "3.7"

networks:
  interviewgenerator-network:

services:
  interviewgenerator-sqlserver:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    ports:
      - "1433:1433"
    environment:
        SA_PASSWORD: "interview@2023"
        ACCEPT_EULA: "Y"
    networks:
      - interviewgenerator-network