apiVersion: apps/v1
kind: Deployment
metadata:
  name: skillcheck-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skillcheck-api
  template:
    metadata:
      labels:
        app: skillcheck-api
    spec:
      containers:
      - name: skillcheck-api
        image: skillcheckregistry.azurecr.io/skillcheck-api:latest
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
  
---

apiVersion: v1
kind: Service
metadata:
  name: skillcheck-api
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: skillcheck-api
