apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-skillcheck-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skillcheck-api
  template:
    metadata:
      labels:
        app: skillcheck-api
    spec:
      containers:
      - name: skillcheck-api
        image: skillcheckregistry.azurecr.io/skillcheck-api:latest
        ports:
        - containerPort: 80