name: Build e deploy para o AKS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configurando a versão do .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.x'
          include-prerelease: true

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: "bff559dc-aa45-4a83-934b-34fdd91ca46a"
          tenant-id: "11dbbfe2-89b8-4549-be10-cec364e59551"
          subscription-id: "f4636e27-86f1-468c-8435-9f35e126e89f"

      - name: Login to ACR
        run: az acr login --name skillcheckregistry

      - name: Build and push Docker image
        run: |
          docker build -f src/InterviewGenerator.Api/Dockerfile -t skillcheckregistry.azurecr.io/skillcheck-api:latest .
          docker push skillcheckregistry.azurecr.io/skillcheck-api:latest

      - name: Set up Kubernetes
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'

      - name: Get AKS credentials
        run: az aks get-credentials --resource-group rg-skillcheck --name cluster-skillcheck

      - name: Deploy to AKS
        run: kubectl apply -f k8s/api-deployment.yaml -n skillcheck-ns
