name: Build e deploy para o Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configurando a versão do .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.x'
          include-prerelease: true

      - name: Build e Publish
        run: |
          dotnet build
          dotnet publish src/InterviewGenerator.Api/InterviewGenerator.Api.csproj -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Iniciando container SQL Server para testes integrados
        run: docker-compose -f "docker-compose.yml" up -d --build

      - name: Testes Unitários
        run: dotnet test tests/InterviewGenerator.UnitTests/InterviewGenerator.UnitTests.csproj

      - name: Testes Integrados
        run: dotnet test tests/InterviewGenerator.IntegrationTests/InterviewGenerator.IntegrationTests.csproj

      - name: Carregando os pacotes para o Job de Deploy
        uses: actions/upload-artifact@v3
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download do artefato para o build job
        uses: actions/download-artifact@v3
        with:
          name: .net-app

      - name: App Settings Variable Substitution
        uses: microsoft/variable-substitution@v1
        with:
          files: 'appsettings.json'
        env:
          ConnectionStrings.DataBase: ${{ secrets.CONNECTIONSTRING }}

      - name: Deploy para o Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'techchallenge'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_807F19EC175144CFA128B491B6EEBBAD }}
          package: .
